<!doctype html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	
		<title>All exceptions empty » Community Questions &amp; Answers » Appcelerator Developer Center</title>
	
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link href="../../related/favicon.png" rel="shortcut icon" type="image/png">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700" rel="stylesheet" type="text/css">
	<link href="//d3ilu1xuwhtfe2.cloudfront.net/e8e0ebd/css/style.css" rel="stylesheet" type="text/css">
	<link href="../../related/qa.css" rel="stylesheet" type="text/css">
	<link href="../../related/hybrid.css" rel="stylesheet" type="text/css">
	
	<link href="../../related/overrides.css" rel="stylesheet" type="text/css">
</head>
<body>

<div class='mast'>    <div class='container'>        <div class='row'>            <div class='col-sm-12'>                <div class='masthead'><h1>Titanium Community Questions & Answer Archive</h1><h2>We felt that 6+ years of knowledge should not die so this is the Titanium Community Questions &amp; Answer Archive</h2></div>            </div>        </div>    </div></div>

<main class="container">
	<div class="row">
		<div class="col-sm-12">
			
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<article class="question-container">
	<div class="question">
		<header>
			<h1>All exceptions empty</h1>
		</header>
		<section>
			<p>This is a strange one. And I am almost positive its not me now….</p>
<p>When i use try catch statements like this:</p>
<pre><code class="hljs">try{

}
catch(<span class="hljs-keyword">e</span>){
    Ti.API.<span class="hljs-keyword">error</span>(<span class="hljs-keyword">e</span>);
    Ti.API.<span class="hljs-keyword">error</span>(JSON.stringify(<span class="hljs-keyword">e</span>));
}
</code></pre><p>Nothing is caught in the exception, but it used to work fine. Honestly I couldn&#39;t say when this started, but I have noticed now that any errors no longer give me a message in the debug log, I have also run my app in debug mode with breakpoints in there and there is nothing in the e object when it gets to the catch.</p>
<p>Any ideas?</p>
<p>Thanks</p>
<p>Studio Version: 3.2.1.201402041146<br>SDK Version 3.2.2</p>

		</section>
		<footer>
			<div class="author">
				&mdash; asked <span title="April 30th 2014, 9:45:45 am">April 30th 2014</span>
				by <span class='authorname'>Matthew Watson</span>
			</div>

			
				<ul class="tags">
					
						<li><span class='tagname'>android</span></li>
					
						<li><span class='tagname'>error</span></li>
					
						<li><span class='tagname'>ios</span></li>
					
						<li><span class='tagname'>titanium</span></li>
					
				</ul>
			

			<section>
				<h5>1 Comment</h5>
				
					<ul class="comments">
					
						<li class="comment">
							<div><p>Without some actual code, I don&#39;t think there&#39;s much to suggest other than not all errors will create an exception object. Network and database interactions usually do. Syntax errors and similar don&#39;t.</p>
</div>
							<div class="author">
								&mdash; commented <span title="April 30th 2014, 11:38:36 am">April 30th 2014</span>
								by <span class='authorname'>Tim Poulsen</span>
							</div>
						</li>
					
					</ul>
				
			</section>
		</footer>
		<aside class="vote-box">
			<div class="score"><span>0</span> Votes</div>
			<div class="answers"><span>0</span> Answers</div>
		</aside>
	</div>

	<hr>

	<h3>0 Answers</h3>

	
</article>

		</div>
		<div class="col-sm-3"></div>
	</div>
	<div class="row"><div class="signoff">The ownership of individual contributions to this community generated content is retained by the authors of their contributions.<br>All trademarks remain the property of the respective owner.</div></div>
</main>


</body>
</html>
