<!doctype html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	
		<title>can I throw an exception in one module and catch it in other? Â» Community Questions &amp; Answers </title>
	
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link href="../../related/favicon.png" rel="shortcut icon" type="image/png">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700" rel="stylesheet" type="text/css">
	<link href="//d3ilu1xuwhtfe2.cloudfront.net/e8e0ebd/css/style.css" rel="stylesheet" type="text/css">
	<link href="../../related/qa.css" rel="stylesheet" type="text/css">
	<link href="../../related/hybrid.css" rel="stylesheet" type="text/css">
	
	<link href="../../related/overrides.css" rel="stylesheet" type="text/css">
</head>
<body>

<div class='mast'>    <div class='container'>        <div class='row'>            <div class='col-sm-12'>                <div class='masthead'><h1>Titanium Community Questions & Answer Archive</h1><h2>We felt that 6+ years of knowledge should not die so this is the Titanium Community Questions &amp; Answer Archive</h2></div>            </div>        </div>    </div></div>

<main class="container">
	<div class="row">
		<div class="col-sm-12">
			
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<article class="question-container">
	<div class="question">
		<header>
			<h1>can I throw an exception in one module and catch it in other?</h1>
		</header>
		<section>
			<p>I have my modules representing objects. I have one method of an object throwing an exception if a condition is not true(it tries to call a web service, and if here was a problem it fires an exception).<br>I also have another object(another module) which calls the method in the previous module which was fireing the custom exception. However I get a error saying uncaught exception, with the location being the first module(the one which fires the custom exemption exception). So can I fire a custom exception in one module and cats it in another?</p>

		</section>
		<footer>
			<div class="author">
				&mdash; asked <span title="July 23rd 2012, 10:32:18 am">July 23rd 2012</span>
				by <span class='authorname'>Ryan popa</span>
			</div>

			
				<ul class="tags">
					
						<li><span class='tagname'>exception</span></li>
					
						<li><span class='tagname'>module</span></li>
					
				</ul>
			

			<section>
				<h5>0 Comments</h5>
				
			</section>
		</footer>
		<aside class="vote-box vote-box-answered">
			<div class="score"><span>0</span> Votes</div>
			<div class="answers"><span>1</span> Answer</div>
		</aside>
	</div>

	<hr>

	<h3>1 Answer</h3>

	
		<ul class="answers">
			
				<li class="answer">
				
					<article class="accepted-answer" id="answer-243625">
						<header>
							<h2><span class="icon-bg icon-check-1"></span>Accepted Answer</h2>
						</header>
				
						<section>
							<p>Assuming you&#39;re using CommonJS modules and using <code>require()</code>, the answer is &quot;yes&quot;.  The following example shows an exception thrown from within a module and caught in the main app.</p>
<p>MyModule.js:</p>
<pre><code class="hljs"><span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">MyModule</span> (<span class="hljs-params"></span>)
</span>{
    <span class="hljs-keyword">throw</span> { message: <span class="hljs-string">'foo'</span> };
}

<span class="hljs-built_in">module</span>.exports = MyModule;
</code></pre><p>app.js:</p>
<pre><code class="hljs"><span class="hljs-comment">// this sets the background color of the master UIView (when there are no windows/tab groups on it)</span>
Titanium.UI.setBackgroundColor(<span class="hljs-string">'#000'</span>);

<span class="hljs-keyword">var</span> win1 = Titanium.UI.createWindow({  
    title:<span class="hljs-string">'Tab 1'</span>,
    backgroundColor:<span class="hljs-string">'#fff'</span>
});

win1.open  ();

<span class="hljs-keyword">var</span> MyModule = <span class="hljs-built_in">require</span> (<span class="hljs-string">'MyModule'</span>);

<span class="hljs-keyword">try</span>
{
    <span class="hljs-keyword">var</span> mm = <span class="hljs-keyword">new</span> MyModule ();
}
<span class="hljs-keyword">catch</span> (e)
{
    alert (e.message);
}
</code></pre>
						</section>
						<footer>
							<div class="author">
								&mdash; answered <span title="July 23rd 2012, 1:07:47 pm">July 23rd 2012</span>
								by <span class='authorname'>Jason Priebe</span><br>
								<a class="icon-bg icon-link" href="question/140044/can-i-throw-an-exception-in-one-module-and-catch-it-in-other#answer-243625" rel="permalink">permalink</a>
							</div>

							<h5>0 Comments</h5>
							
						</footer>
						<aside class="vote-box vote-box-answered">
							<div class="score"><span>0</span> Votes</div>
						</aside>
					</article>
				</li>
			
		</ul>
	
</article>

		</div>
		<div class="col-sm-3"></div>
	</div>
	<div class="row"><div class="signoff">The ownership of individual contributions to this community generated content is retained by the authors of their contributions.<br>All trademarks remain the property of the respective owner.</div></div>
</main>


</body>
</html>
